// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backText': string;
  'root': string;
  'textContent': string;
  'wrap': string;
  'wrapContent': string;
}
export const cssExports: CssExports;
export default cssExports;
