// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'pageHeader': string;
  'pokemonCardPreview': string;
  'pokemonGallery': string;
  'root': string;
  'searchInput': string;
}
export const cssExports: CssExports;
export default cssExports;
